# Logistic Regression

## Fitting a model in sklearn

In [63]:
# Import libraries and data
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression

codecademyU = pd.read_csv('data.csv')
print(codecademyU.head())

   hours_studied  practice_test  passed_exam
0              0             55            0
1              1             75            0
2              2             32            0
3              3             80            0
4              4             75            0


In [65]:
# Import pandas and the data
import pandas as pd
codecademyU = pd.read_csv('data.csv')


# Separate out X and y
X = codecademyU[['hours_studied', 'practice_test']]
y = codecademyU.passed_exam


# Transform X
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X)
X = scaler.transform(X)


# Split data into training and testing sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state = 27)


# Create and fit the logistic regression model here:
from sklearn.linear_model import LogisticRegression


cc_lr = LogisticRegression()
cc_lr.fit(X_train, y_train)
# Print the intercept and coefficients here:
print(cc_lr.coef_)
print(cc_lr.intercept_)

[[1.5100409  0.12002228]]
[-0.13173123]


## Predictions in sklearn

Using a trained model, we can predict whether new datapoints belong to the positive class (the group labeled as 1) using the .predict() method. The input is a matrix of features and the output is a vector of predicted labels, 1 or 0.

print(model.predict(features))

Sample output: [0 1 1 0 0]

If we are more interested in the **predicted probability** of group membership, we can use the .predict_proba() method. The input to predict_proba() is also a matrix of features and the output is an array of probabilities, ranging from 0 to 1:

print(model.predict_proba(features)[:,1])

Sample output: [0.32 0.75  0.55 0.20 0.44]


By default, .predict_proba() returns the probability of class membership for both possible groups. In the example code above, we’ve only printed out the probability of belonging to the positive class. Notice that datapoints with predicted probabilities greater than 0.5 (the second and third datapoints in this example) were classified as 1s by the .predict() method. This is a process known as thresholding. As we can see here, sklearn sets the default classification threshold probability as 0.5.

In [85]:
# Print out the predicted outcomes for the test data
print(cc_lr.predict(X_test))
print()
print(X_test)
print()
# Print out the predicted probabilities for the test data
print(cc_lr.predict_proba(X_test))
print()
# Print out the true outcomes for the test data
print(y_test)

[0 1 0 1 1]

[[-0.43355498  0.29722219]
 [ 0.95382097  0.29722219]
 [-1.64750894 -1.79313169]
 [ 0.26013299  0.42786931]
 [ 1.30066495  0.62383999]]

[[0.67934073 0.32065927]
 [0.2068119  0.7931881 ]
 [0.94452517 0.05547483]
 [0.42252072 0.57747928]
 [0.12929566 0.87070434]]

7     0
15    1
0     0
11    0
17    1
Name: passed_exam, dtype: int64


You should see that the fourth datapoint was incorrectly classified as having passed the exam; however, the predicted probability of passing for this datapoint was only 57.7%, which is much lower than the other students who were correctly predicted to pass the exam (79.3% and 87.1%, respectively).